image: node:16

pipelines:
  default:
    - step:
        name: Build and Test
        runs-on: self.hosted
        caches:
          - node
        script:
          - npm install
          - npm test
