name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    environment:
      name: test
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v2

      - name: GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE

      - name: PWD
        run: pwd

      - name: Files
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
